const yup = require('yup');

const schema = yup.object().shape({
  location: yup.string().trim(),
  address: yup.string().trim(),
  cohorts: yup.string().trim(),
  mobileNumber: yup.number().min(10).max(18),
  age: yup.number().min(18),
  motivation: yup.string().trim(),
  englishSpeaking: yup.string().trim(),
  englishUnderstanding: yup.string().trim(),
  employmentStatus: yup.string().trim(),
  jobTitle: yup.string().trim(),
  university: yup.string().trim(),
  specialization: yup.string().trim(),
  cvLink: yup.string().trim(),
  codingExperience: yup.string().trim(),
  primaryMotivation: yup.string().trim(),
  caReading: yup.string().trim(),
  available: yup.boolean(),
  githubLink: yup.string().trim(),
  joinDiscord: yup.boolean(),
  freeCodeCampPoints: yup.number().min(0).max(1500),
  freeCodeCampTopics: yup.boolean(),
  freeCodeCampLink: yup.string().trim(),
  codeWarsLink: yup.string().trim(),
  codeWarsKyu: yup.string().trim(),
  technicalTasks: yup.boolean(),
  technicalTasksLinks: yup.string().trim(),
  projectGithubLink: yup.string().trim(),
});

const updateApplicant = (
  location,
  address,
  cohorts,
  mobileNumber,
  age,
  motivation,
  englishSpeaking,
  englishUnderstanding,
  employmentStatus,
  jobTitle,
  university,
  specialization,
  cvLink,
  codingExperience,
  primaryMotivation,
  caReading,
  available,
  githubLink,
  joinDiscord,
  freeCodeCampPoints,
  freeCodeCampTopics,
  freeCodeCampLink,
  codeWarsLink,
  codeWarsKyu,
  technicalTasks,
  technicalTasksLinks,
  projectGithubLink
) =>
  schema.isValid({
    location,
    address,
    cohorts,
    mobileNumber,
    age,
    motivation,
    englishSpeaking,
    englishUnderstanding,
    employmentStatus,
    jobTitle,
    university,
    specialization,
    cvLink,
    codingExperience,
    primaryMotivation,
    caReading,
    available,
    githubLink,
    joinDiscord,
    freeCodeCampPoints,
    freeCodeCampTopics,
    freeCodeCampLink,
    codeWarsLink,
    codeWarsKyu,
    technicalTasks,
    technicalTasksLinks,
    projectGithubLink,
  });

module.exports = updateApplicant;
